server:  port: 18769
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/spring:  application:    name: zl-gateway  cloud:    gateway:      routes:      - id: zl-order        uri: lb://ZL-ORDER        predicates:          - path: /order/**          