server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/nolimits/myc-config.git
          skipSslValidation: true
          force-pull: true
          username: nolimits@163.com
          password: xzawdsq07104
          search-paths: /config
  application:
    name: zl-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/